superhero_creator/superhero_creator/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url = '/superheroes/')),
    path('details/', include('superheroes.urls')),
    path('edit/', include('superheroes.urls')),
    path('delete/', include('superheroes.urls')),
]

superhero_creator/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('details/<int:hero_id>', views.details, name = 'details'),
    path('new/', views.create, name ='create'),
    path('edit/<int:hero_id>', views.edit, name = 'edit'),
    path('delete/<int:hero_id>', views.delete , name = 'delete'),
]

superhero_creator/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_creator/superheroes/views.py
from django.db.models.fields import CommaSeparatedIntegerField
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Superhero


#* Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def details(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/details.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary')
        secondary_ability = request.POST.get('secondary')
        catch_phrase = request.POST.get('catch_phrase')

        #?Instantiate Superhero Objects
        new_hero = Superhero(
            name = name, 
            alter_ego = alter_ego,
            primary_ability = primary_ability, 
            secondary_ability = secondary_ability, 
            catch_phrase = catch_phrase,
        )

        #?save to Superhero DB
        new_hero.save()
        #?return user to superheroes/index.html
        return HttpResponseRedirect(reverse('superheroes:index'))

    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    edit_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'edit_hero': edit_hero
    }

    if request.method == "POST":
        edit_hero.name = request.POST.get('name')
        edit_hero.alter_ego = request.POST.get('alter_ego')
        edit_hero.primary_ability = request.POST.get('primary')
        edit_hero.secondary_ability = request.POST.get('secondary')
        edit_hero.catch_phrase = request.POST.get('catch_phrase')
        
        #?save to Superhero DB
        edit_hero.save()
        #?return user to superheroes/index.html
        return HttpResponseRedirect(reverse('superheroes:index'))
        
    else:
        return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    del_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'del_hero': del_hero
    }

    if request.method == "POST":
        del_hero.delete()
        #?return user to superheroes/index.html
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/delete.html', context)

superhero_creator/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Hero | Superhero</title>
</head>
<body>
    <h1>Create a new superhero</h1>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name" placeholder="Superman"><br>
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" placeholder="Clark Kent"><br>
        Primary Ability: <input type="text" name="primary" id="primary" placeholder="Superhuman Strength"><br>
        Secondary Ability: <input type="text" name="secondary" id="secondary" placeholder="Flight"><br>
        Catchphrase: <input type="text" name="catch_phrase" id="catch_phrase" placeholder="Up, up, and away!"><br>
        <input type="submit" value="Add!">
    </form>
    <h3><a href="{% url 'superheroes:index' %}">Return Home</a></h3>


</body>
</html>

superhero_creator/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete | Hero</title>
</head>
<body>
    <h1>Delete Hero</h1>
    <h2>{{del_hero.name}} Details</h2>
    <ul>
        <li>Name: {{del_hero.name}}</li>
        <li>Alter Ego: {{del_hero.alter_ego}}</li>
        <li>Primary Ability: {{del_hero.primary_ability}}</li>
        <li>Secondary Ability: {{del_hero.secondary_ability}}</li>
        <li>Catchphrase: {{del_hero.catch_phrase}}</li>
    </ul>
    <h3><a href="{% url 'superheroes:index' %}">Return Home</a></h3>
    <h3>Are You sure you want to delete {{del_hero.name}}?</h3>
    <form action="{% url 'superheroes:delete' del_hero.id %}" method="post">
        {% csrf_token %}
        <input type="radio" id='yes' name='yes'>
        <label for='html'>Yes</label>
        <br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

superhero_creator/superheroes/templates/superheroes/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details | Hero</title>
</head>
<body>
    <h1>Hero Details</h1>
    <h2>{{single_hero}} Details</h2>
    <ul>
        <li>Alter Ego: {{single_hero.alter_ego}}</li>
        <li>Primary Ability: {{single_hero.primary_ability}}</li>
        <li>Secondary Ability: {{single_hero.secondary_ability}}</li>
        <li>Catchphrase: {{single_hero.catch_phrase}}</li>
    </ul>
    <h3><a href="{% url 'superheroes:edit' single_hero.id %}">Edit Hero</a></h3>
    <h3><a href="{% url 'superheroes:delete' single_hero.id %}">Delete Hero</a></h3>
    <h3><a href="{% url 'superheroes:index' %}">Return Home</a></h3>
</body>
</html>

superhero_creator/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit | Hero</title>
</head>
<body>
    <h1>Edit Hero</h1>
    <h2>{{edit_hero}} Current Details</h2>
    <ul>
        <li>Name: {{edit_hero.name}}</li>
        <li>Alter Ego: {{edit_hero.alter_ego}}</li>
        <li>Primary Ability: {{edit_hero.primary_ability}}</li>
        <li>Secondary Ability: {{edit_hero.secondary_ability}}</li>
        <li>Catchphrase: {{edit_hero.catch_phrase}}</li>
    </ul>
    <h3><a href="{% url 'superheroes:delete' edit_hero.id %}">Delete Hero</a></h3>
    <h3><a href="{% url 'superheroes:index' %}">Return Home</a></h3>
    <br>
    <h2>{{edit_hero}} Edit Details</h2>
    <form action="{% url 'superheroes:edit' edit_hero.id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name" value='{{edit_hero.name}}'><br>
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" value='{{edit_hero.alter_ego}}'><br>
        Primary Ability: <input type="text" name="primary" id="primary" value='{{edit_hero.primary_ability}}'><br>
        Secondary Ability: <input type="text" name="secondary" id="secondary" value='{{edit_hero.secondary_ability}}'><br>
        Catchphrase: <input type="text" name="catch_phrase" id="catch_phrase" value='{{edit_hero.catch_phrase}}'><br>
        <input type="submit" value="Submit Changes">
    </form>
</body>
</html>

superhero_creator/superheroes/templates/superheroes/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'superheroes/css/style.css' %}">
    <title>Home | Superhero</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <img src="{% static 'superheroes/images/wonder_woman.jpg' %}" alt="Wonder Woman">
    <img src="{% static 'superheroes/images/flash.jpg' %}" alt="Flash">
    <img src="{% static 'superheroes/images/batman.jpg' %}" alt="Batman">
    <ul>
        {% for hero in all_heroes %}
        <li> <h2>{{hero.name}} - <a href="{% url 'superheroes:details' hero.id %}">Click for Hero Details!</a></h2> 
        </li>
        {% endfor %}
    </ul>
    <h2><a href="{% url 'superheroes:create' %}">Create a new hero!</a></h2>
</body>
</html>